# ============================================
# Minimax Helper Watcher
# ============================================

. "$PSScriptRoot/utils/logger.ps1"

$config = @{
    WatchPath = ".dev-flow/handoff/to-minimax*.md"
    ResultDir = ".dev-flow/results"
    PollInterval = 5
    MaxTokens = 2000
    ContextLimit = 10000  # ~10K tokens
}

# ─────────────────────────────────────────
# Minimax API Functions
# ─────────────────────────────────────────

function Test-ContextSize {
    param([string]$Content)
    
    # Simple token estimation (1 token ≈ 4 chars)
    $estimatedTokens = $Content.Length / 4
    
    if ($estimatedTokens -gt $config.ContextLimit) {
        Write-Log "Context too large: $estimatedTokens tokens (limit: $($config.ContextLimit))" "WARN"
        return $false
    }
    
    Write-Log "Context size OK: ~$([math]::Round($estimatedTokens)) tokens" "INFO"
    return $true
}

function Invoke-MinimaxAPI {
    param([string]$TaskContent)
    
    Write-Log "Calling minimax API..." "INFO"
    
    $apiKey = $env:NVIDIA_API_KEY
    if (-not $apiKey) {
        Write-Log "NVIDIA_API_KEY not found in environment variables" "ERROR"
        return $null
    }
    
    try {
        $body = @{
            model = "minimaxai/minimax-m2.7"
            messages = @(
                @{
                    role = "user"
                    content = $TaskContent
                }
            )
            max_tokens = $config.MaxTokens
            temperature = 0.7
        } | ConvertTo-Json -Depth 10
        
        # Note: Update this URL based on actual minimax API endpoint
        # This is a placeholder - check NVIDIA documentation for correct endpoint
        $response = Invoke-RestMethod -Uri "https://integrate.api.nvidia.com/v1" `
            -Method Post `
            -Headers @{
                "Authorization" = "Bearer $apiKey"
                "Content-Type" = "application/json"
            } `
            -Body $body `
            -TimeoutSec 30
        
        $result = $response.choices[0].message.content
        
        Write-Log "minimax API call successful" "INFO"
        
        return $result
        
    } catch {
        Write-Log "minimax API call failed: $_" "ERROR"
        return $null
    }
}

# ─────────────────────────────────────────
# Task Type Handlers
# ─────────────────────────────────────────

function Get-TaskType {
    param([string]$Content)
    
    # Identify task type from content
    if ($Content -match 'task_type:\s*(\w+)') {
        return $matches[1]
    }
    
    # Auto-detect from keywords
    if ($Content -match 'format|prettier|lint') {
        return "format"
    } elseif ($Content -match 'mock.*data|test.*data|generate.*data') {
        return "mock_data"
    } elseif ($Content -match 'translate|翻譯|localization') {
        return "translate"
    } elseif ($Content -match 'document|JSDoc|comment') {
        return "docs"
    } elseif ($Content -match '\.env|config|configuration') {
        return "config"
    }
    
    return "unknown"
}

function Save-MinimaxResult {
    param(
        [string]$TaskId,
        [string]$Result,
        [string]$TaskType
    )
    
    if (-not (Test-Path $config.ResultDir)) {
        New-Item -ItemType Directory -Path $config.ResultDir -Force | Out-Null
    }
    
    $timestamp = Get-Date -Format 'o'
    
    $resultContent = @"
---
task_id: $TaskId
task_type: $TaskType
processed_at: $timestamp
processed_by: minimax-m2.7
---

# Minimax Result: $TaskId

## Task Type
$TaskType

## Result
$Result

---

Generated by minimax helper at $timestamp
"@
    
    $resultFile = Join-Path $config.ResultDir "minimax-result-$TaskId.md"
    $resultContent | Out-File $resultFile -Encoding UTF8 -Force
    
    Write-Log "Result saved: $resultFile" "INFO"
}

# ─────────────────────────────────────────
# Main Loop
# ─────────────────────────────────────────

Write-Log "Minimax helper watcher started" "INFO"
Write-Log "Press Ctrl+C to stop" "INFO"
Write-Host ""

while ($true) {
    try {
        $taskFiles = Get-ChildItem $config.WatchPath -ErrorAction SilentlyContinue
        
        foreach ($taskFile in $taskFiles) {
            $taskId = [regex]::Match($taskFile.Name, 'to-minimax-(.+)\.md').Groups[1].Value
            
            Write-Log "=== Processing minimax task: $taskId ===" "INFO"
            
            # Read task content
            $taskContent = Get-Content $taskFile.FullName -Raw
            
            # Identify task type
            $taskType = Get-TaskType -Content $taskContent
            Write-Log "Task type: $taskType" "INFO"
            
            # Check context size
            if (-not (Test-ContextSize -Content $taskContent)) {
                Write-Log "Task too complex for minimax, escalating to human" "ERROR"
                
                # Move to human intervention
                $humanFile = $taskFile.FullName -replace 'to-minimax', 'to-human'
                Move-Item $taskFile.FullName $humanFile -Force
                
                Write-Log "Moved to human queue: $humanFile" "WARN"
                continue
            }
            
            # Call minimax API
            $result = Invoke-MinimaxAPI -TaskContent $taskContent
            
            if ($result) {
                # Save result
                Save-MinimaxResult -TaskId $taskId -Result $result -TaskType $taskType
                
                Write-Log "=== minimax task completed ===" "INFO"
            } else {
                Write-Log "minimax processing failed for task $taskId" "ERROR"
            }
            
            # Remove processed task
            Remove-Item $taskFile.FullName -Force
            Write-Host ""
        }
        
        Start-Sleep -Seconds $config.PollInterval
        
    } catch {
        Write-Log "Error in main loop: $_" "ERROR"
        Start-Sleep -Seconds $config.PollInterval
    }
}
